#!/bin/bash
# Bundle project into a self-extracting install.sh

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$SCRIPT_DIR/install.sh"

echo "================================================"
echo "Local Agent Server - Bundle"
echo "================================================"
echo ""

echo "📦 Packing source files..."
TMPTAR=$(mktemp /tmp/local-agent-server-XXXXXX.tar.gz)
tar -czf "$TMPTAR" \
    --exclude='src/venv' \
    --exclude='src/__pycache__' \
    --exclude='src/*.pyc' \
    --exclude='src/.env' \
    -C "$PROJECT_DIR" src/

PAYLOAD_SIZE=$(du -sh "$TMPTAR" | cut -f1)
echo "   ✓ Packed (${PAYLOAD_SIZE})"

echo ""
echo "📝 Generating install.sh..."

cat > "$OUTPUT" << 'HEADER'
#!/bin/bash
# Local Agent Server - Self-extracting Installer
# Generated by bundle.sh — do not edit manually
# Supports: Debian/Ubuntu (apt) | CentOS/RHEL 7 (yum) | CentOS/RHEL 8+/Fedora (dnf) | AlmaLinux

set -e

echo "================================================"
echo "Local Agent Server - One-liner Installer"
echo "================================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Please run as root (use sudo)"
    exit 1
fi

INSTALL_DIR="/var/www/local-agent-server"
SERVICE_USER="local-agent"
PYTHON_BIN=""

# ── Find Python 3.8+ ──────────────────────────────────────────────────────────
find_python() {
    local CANDIDATES=(
        /opt/python38/bin/python3.8
        /opt/python39/bin/python3.9
        /opt/python310/bin/python3.10
        /opt/python311/bin/python3.11
        /usr/local/bin/python3.11
        /usr/local/bin/python3.10
        /usr/local/bin/python3.9
        /usr/local/bin/python3.8
        python3.11
        python3.10
        python3.9
        python3.8
        python3
    )
    for candidate in "${CANDIDATES[@]}"; do
        if command -v "$candidate" &>/dev/null || [ -x "$candidate" ]; then
            local ver
            ver=$("$candidate" -c "import sys; print(sys.version_info >= (3,8))" 2>/dev/null)
            if [ "$ver" = "True" ]; then
                echo "$candidate"
                return 0
            fi
        fi
    done
    return 1
}

# ── Detect OS and install dependencies ───────────────────────────────────────
echo "📦 Detecting OS and installing system dependencies..."

if command -v apt-get &>/dev/null; then
    echo "   Detected: Debian / Ubuntu"
    apt-get update -qq
    apt-get install -y python3 python3-venv python3-pip rsync

elif command -v dnf &>/dev/null; then
    echo "   Detected: Fedora / RHEL 8+ / CentOS Stream / AlmaLinux"
    dnf install -y python3 python3-pip rsync
    # Install SELinux tools if SELinux is present
    if command -v getenforce &>/dev/null; then
        dnf install -y policycoreutils-python-utils 2>/dev/null || true
    fi

elif command -v yum &>/dev/null; then
    echo "   Detected: CentOS 7 / RHEL 7"
    yum install -y rsync 2>/dev/null || true
    if ! find_python &>/dev/null; then
        echo "   Python 3.8+ not found, installing from IUS repo..."
        yum install -y epel-release 2>/dev/null || true
        yum install -y https://repo.ius.io/ius-release-el7.rpm 2>/dev/null || true
        yum install -y python311 python311-pip || {
            echo "   ⚠️  IUS repo failed, trying SCL..."
            yum install -y centos-release-scl 2>/dev/null || true
            yum install -y rh-python38 || {
                echo "❌ Could not install Python 3.8+. Please install manually then re-run."
                exit 1
            }
        }
    else
        echo "   Python 3.8+ already installed, skipping."
    fi

else
    echo "❌ Unsupported OS — no apt-get, dnf, or yum found"
    exit 1
fi

# ── Resolve Python binary ─────────────────────────────────────────────────────
PYTHON_BIN=$(find_python) || {
    echo "❌ Python 3.8+ not found after install. Please check your environment."
    exit 1
}
echo "   ✓ Using Python: $PYTHON_BIN ($($PYTHON_BIN --version))"
echo "   ✓ Dependencies installed"

# ── Create dedicated service user (NOT nobody) ────────────────────────────────
echo ""
echo "👤 Creating service user '$SERVICE_USER'..."
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd -r -s /sbin/nologin -d "$INSTALL_DIR" -c "Local Agent Server" "$SERVICE_USER"
    echo "   ✓ User '$SERVICE_USER' created"
else
    echo "   ✓ User '$SERVICE_USER' already exists"
fi

# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo "📁 Creating directories..."
mkdir -p $INSTALL_DIR/src
mkdir -p /var/log/local-agent-server

echo ""
echo "📋 Extracting source files..."
TMPTAR=$(mktemp /tmp/local-agent-server-XXXXXX.tar.gz)
base64 -d << 'PAYLOAD' > "$TMPTAR"
HEADER

# Append base64 payload
base64 -w 76 "$TMPTAR" >> "$OUTPUT"

# Append footer
cat >> "$OUTPUT" << 'FOOTER'
PAYLOAD
tar -xzf "$TMPTAR" -C "$INSTALL_DIR/src" --strip-components=1 src/
rm -f "$TMPTAR"
echo "   ✓ Source files extracted"

echo ""
echo "🐍 Setting up Python virtual environment..."
rm -rf $INSTALL_DIR/src/venv
$PYTHON_BIN -m venv $INSTALL_DIR/src/venv
VENV_PIP="$INSTALL_DIR/src/venv/bin/pip"

$VENV_PIP install --upgrade pip setuptools wheel \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org

$VENV_PIP install gunicorn \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org

$VENV_PIP install -r $INSTALL_DIR/src/requirements.txt \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org
echo "   ✓ Virtual environment ready"

echo ""
echo "👤 Setting permissions..."
chown -R "$SERVICE_USER":"$SERVICE_USER" $INSTALL_DIR
chown -R "$SERVICE_USER":"$SERVICE_USER" /var/log/local-agent-server
chmod -R 755 $INSTALL_DIR
chmod +x $INSTALL_DIR/src/venv/bin/gunicorn

# ── Fix SELinux (AlmaLinux / RHEL / CentOS) ───────────────────────────────────
if command -v getenforce &>/dev/null && [ "$(getenforce)" = "Enforcing" ]; then
    echo ""
    echo "🔒 SELinux detected (Enforcing) — applying context fixes..."

    # Set correct SELinux context for venv binaries
    chcon -R -t bin_t $INSTALL_DIR/src/venv/bin/ 2>/dev/null || true

    # Set correct context for app files
    chcon -R -t httpd_sys_content_t $INSTALL_DIR/src/ 2>/dev/null || true

    # Set correct context for log directory
    chcon -R -t httpd_log_t /var/log/local-agent-server/ 2>/dev/null || true

    restorecon -R $INSTALL_DIR 2>/dev/null || true

    # Generate and apply SELinux policy from audit log if audit2allow is available
    if command -v audit2allow &>/dev/null; then
        echo "   Generating SELinux policy from audit log..."
        # Start service temporarily to generate denials, then build policy
        systemctl start local-agent-server 2>/dev/null || true
        sleep 3
        systemctl stop local-agent-server 2>/dev/null || true
        ausearch -c 'gunicorn' --raw 2>/dev/null | audit2allow -M local-agent-policy 2>/dev/null && \
            semodule -i local-agent-policy.pp 2>/dev/null && \
            echo "   ✓ SELinux policy applied" || \
            echo "   ⚠️  No audit denials found yet — policy will auto-apply on first run"
    fi

    echo "   ✓ SELinux context configured"
fi
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo "🔧 Setting up systemd service..."
cat > /etc/systemd/system/local-agent-server.service << SERVICE
[Unit]
Description=Local Agent Server - Flask Backend
After=network.target

[Service]
Type=notify
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}/src
Environment="PATH=${INSTALL_DIR}/src/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=${INSTALL_DIR}/src/venv/bin/gunicorn \
    --workers 2 \
    --bind 127.0.0.1:5000 \
    --timeout 120 \
    --access-logfile /var/log/local-agent-server/access.log \
    --error-logfile /var/log/local-agent-server/error.log \
    app:app
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
echo "   ✓ Service registered"

echo ""
echo "================================================"
echo "✅ Installation completed!"
echo "================================================"
echo ""
echo "⚠️  IMPORTANT: Edit config before starting:"
echo "   nano $INSTALL_DIR/src/config.json"
echo "   - Change auth_token"
echo "   - Add your repositories"
echo ""
echo "Then start the service:"
echo "   systemctl start local-agent-server"
echo "   systemctl enable local-agent-server"
echo ""
echo "If SELinux still blocks (AlmaLinux/RHEL), run:"
echo "   sudo ausearch -c 'gunicorn' --raw | sudo audit2allow -M local-agent-policy"
echo "   sudo semodule -i local-agent-policy.pp"
echo "   sudo systemctl start local-agent-server"
echo ""
FOOTER

rm -f "$TMPTAR"
chmod +x "$OUTPUT"

INSTALL_SIZE=$(du -sh "$OUTPUT" | cut -f1)
echo "   ✓ install.sh generated (${INSTALL_SIZE})"
echo ""
echo "================================================"
echo "✅ Bundle complete!"
echo "================================================"
echo ""
echo "📄 Output: $SCRIPT_DIR/install.sh"
echo ""
echo "📋 One-liner for other machines:"
echo "   curl -sSL https://<your-ngrok-url>/install | sudo bash"
echo ""