"""
Local Agent Server - Main Application
Multi-repository code agent for Claude web chat
"""
import os
import importlib
import json
from pathlib import Path

from flask import Flask, send_file, abort
from flask_cors import CORS

# Initialize Flask app
app = Flask(__name__)
CORS(app)

# Load configuration
with open("config.json", "r") as f:
    CONFIG = json.load(f)

# Server version
SERVER_VERSION = "2.0.0"

# Initialize middleware
from utils.middleware import init_middleware
middleware = init_middleware(app, version=SERVER_VERSION)

# Initialize repository manager
from config import init_repo_manager
repo_manager = init_repo_manager("config.json")

print("=" * 60)
print("🚀 Local Agent Server - Multi-Repository")
print("=" * 60)
print(f"📦 Version: {SERVER_VERSION}")
print(f"📁 Repositories loaded: {len(repo_manager.list_repositories())}")
for code, repo in repo_manager.list_repositories().items():
    print(f"   • {code}: {repo['path']}")
print(f"🔑 Auth Token: {CONFIG['auth_token']}")
print(f"🌐 Host: {CONFIG['host']}:{CONFIG['port']}")
print("=" * 60)
print()

# ── Install endpoint ──────────────────────────────────────────────────────────
# Serves the self-extracting install.sh generated by scripts/bundle.sh
# No auth required — intentionally public for one-liner installation
# Usage on another machine:
#   curl -sSL https://<ngrok-url>/install | sudo bash

@app.route('/install')
def serve_installer():
    path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..', 'scripts', 'install.sh')
    )
    if not os.path.exists(path):
        abort(404, description="install.sh not found. Run: bash scripts/bundle.sh")
    return send_file(path, mimetype='text/x-shellscript', as_attachment=False)

# ─────────────────────────────────────────────────────────────────────────────

# Auto-register all routes
routes_dir = Path("routes")
registered_count = 0
for category_dir in sorted(routes_dir.iterdir()):
    if category_dir.is_dir() and not category_dir.name.startswith("__"):
        for route_file in sorted(category_dir.glob("*.py")):
            if route_file.stem != "__init__":
                module_path = f"routes.{category_dir.name}.{route_file.stem}"
                try:
                    module = importlib.import_module(module_path)
                    module.register(app)
                    registered_count += 1
                except Exception as e:
                    print(f"⚠️  Failed to load {module_path}: {e}")

print(f"✓ Registered {registered_count} endpoints")
print(f"✓ Middleware initialized")
print()
print("⚠️  IMPORTANT:")
print("   1. Change auth_token in config.json!")
print("   2. Use ngrok/cloudflared to expose to internet")
print("   3. Provide Claude with: URL + Bearer token")
print()
print("🎉 Server ready!")
print("=" * 60)
print()

if __name__ == "__main__":
    app.run(host=CONFIG["host"], port=CONFIG["port"], debug=CONFIG["debug"])
